wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.7.9
    t:
      1:
      - 1
      - 5
      - 9
      4: 3.7.9
      5: 0.11.1
      8:
      - 2
      - 5
